/**
 * Determines the level of logging that the function will output. This enables
 * us to reduce the amount of "noise" generated by a battle-tested function,
 * whilst enabling us to output additional logging on a new version.
 *
 * Setting `process.env.LOG_LEVEL` will overwrite the default value of `"info"`
 * for this variable.
 *
 * @type {String}
 */
export const LOG_LEVEL = process.env.LOG_LEVEL || 'info';

/**
 * The AWS Region that this Lambda function is currently executing in.
 *
 * _Note: This is normally populated by the Lambda execution environment._
 *
 * @type {String}
 */
export const { AWS_REGION } = process.env;
