FROM node:6.6

ENV PATH=/node_modules/.bin:$PATH NODE_PATH=$NODE_PATH:/node_modules

WORKDIR /

ADD package.json /package.json

RUN npm install -g aws-sdk && npm install

ADD . /service

WORKDIR /service
