AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates a build, test and deployment pipeline."

Parameters:

  Branch:
    Type: String
    Default: master
    Description: Branch to use from the repository.

  Project:
    Type: String
    Default: aws-pipeline-transfer
    Description: The name this project will be identified as inside AWS.

  ProjectExecutionRole:
    Type: String
    Description: The pre-created IAM role to use.

  ArtifactStore:
    Type: String
    Description: The S3 bucket to use as the artifact store.

  RepositoryName:
    Type: String
    Description: The name of the repository that triggers this pipeline

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RestartExecutionOnUpdate: false
      ArtifactStore:
        Location: !Ref ArtifactStore
        Type: S3
      RoleArn: !Ref ProjectExecutionRole
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                BranchName: !Ref Branch
                RepositoryName: !Ref RepositoryName
        - Name: Build
          Actions:
            - Name: Build
              RunOrder: 2
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref Build
        - Name: Release
          Actions:
            - Name: Create
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM
                RoleArn: !Ref ProjectExecutionRole
                StackName: !Sub "${Project}-${Branch}-release"
                ChangeSetName: !Sub "${Project}-${Branch}-release-cs"
                TemplatePath: BuildOutput::template.yml
                ParameterOverrides:
                  Fn::Sub:
                    - |
                      {
                        "Name": "${Name}"
                      }
                    - Name:
                        Ref: Project
            - Name: Deploy
              RunOrder: 3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                Capabilities: CAPABILITY_IAM
                ChangeSetName: !Sub "${Project}-${Branch}-release-cs"
                RoleArn: !Ref ProjectExecutionRole
                StackName: !Sub "${Project}-${Branch}-release"

  Build:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref Project
      TimeoutInMinutes: 10
      ServiceRole: !Ref ProjectExecutionRole
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:6.3.1
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !Ref ArtifactStore
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
      Artifacts:
        Type: CODEPIPELINE
